In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
import nltk

In [3]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [4]:
data = pd.read_csv(r"C:\Users\nitisha.reddy\Documents\Intellipaat\Datasets\Movie_recommendation\IMDB Dataset.csv",encoding='unicode_escape')

In [5]:
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
from nltk.corpus import stopwords

In [9]:
from tqdm import tqdm

In [10]:
corpus=[]
for i in tqdm(range(0,data.shape[0])):
    review = re.sub('[^a-zA-Z]', ' ', data['review'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)
    

100%|█████████████████████████████████████████████████████████████████████████| 50000/50000 [17:32:07<00:00,  1.26s/it]


In [11]:
corpus[0]

'one reviewer mentioned watching oz episode hooked right exactly happened br br first thing struck oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use word br br called oz nickname given oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home many aryan muslim gangsta latino christian italian irish scuffle death stare dodgy dealing shady agreement never far away br br would say main appeal show due fact go show dare forget pretty picture painted mainstream audience forget charm forget romance oz mess around first episode ever saw struck nasty surreal say ready watched developed taste oz got accustomed high level graphic violence violence injustice crooked guard sold nickel inmate kill order get away well mannered middle class inmate turned prison bitch due lack street skill prison experi

In [12]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [14]:
words = []
for i in tqdm(corpus):
    sent_token = sent_tokenize(i)
    for j in sent_token:
        words.append(simple_preprocess(j))

100%|██████████████████████████████████████████████████████████████████████████| 50000/50000 [00:16<00:00, 3015.00it/s]


In [69]:
import gensim
model1 = gensim.models.Word2Vec(words,window=5,min_count=2)

In [70]:
def avgword2vec(doc):
    return np.mean([model1.wv[word] for word in doc if word in model1.wv.index_to_key],axis=0)

In [71]:
len(model1.wv.index_to_key)

54976

In [73]:
from tqdm import tqdm

In [74]:
X=[]
for i in tqdm(range(len(words))):
    X.append(avgword2vec(words[i]))


100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [17:49<00:00, 46.73it/s]


In [91]:
import bz2file as bz2

In [94]:
def compressed_pickle(title, data):
    with bz2.BZ2File(title + ".pbz2", "w") as f:
        pickle.dump(data, f)

In [96]:
type(model1)

gensim.models.word2vec.Word2Vec

In [124]:
x=model1.wv

In [123]:
lst = list(model1.wv.index_to_key)

In [125]:
for i in lst:
    z=[]
    for j in range(100):
        z.append(float("{0:.2f}".format(x[i][j])))
    
    model1.wv[i]=np.array(z)

In [127]:
model1.wv['movie']

array([ 0.2 , -0.25, -1.35, -0.23,  0.92,  0.79,  1.46,  0.33, -0.06,
        0.2 ,  0.68,  1.75, -1.39,  1.92,  0.07, -0.35,  1.22,  1.06,
       -3.66,  0.18, -0.08,  0.24,  2.13, -0.57,  1.12, -0.23, -0.79,
        1.61, -0.25,  1.5 , -0.57, -1.85,  0.91, -1.21, -1.37,  0.63,
        1.79,  0.36,  2.45,  1.81,  0.39, -0.47,  0.07, -0.57,  0.36,
        0.63,  0.14,  0.97, -1.17, -0.65,  1.19, -0.44, -0.51, -0.92,
       -0.4 , -1.63,  0.65, -1.18, -0.52,  0.69,  0.52, -0.68, -1.1 ,
       -0.72, -0.21,  1.4 ,  0.28, -0.07, -0.52,  0.83,  0.93,  1.6 ,
       -2.6 ,  1.24,  2.18, -1.61, -0.11,  1.76,  0.83, -0.56, -1.74,
        1.08,  0.24,  0.98, -0.64,  0.21,  1.45, -2.26, -2.14,  0.36,
        1.07, -1.4 ,  0.7 , -0.33,  1.62,  0.2 ,  0.44, -0.31, -0.97,
        0.6 ], dtype=float32)

In [128]:
model2=model1.wv

In [131]:
model2['film']

array([-0.02, -0.32, -1.14, -0.02,  0.4 ,  1.28,  0.33,  1.32,  0.83,
        0.5 , -0.02,  1.44, -0.51,  1.57, -0.23, -0.9 ,  1.7 ,  1.11,
       -3.61,  0.01,  0.14,  0.29,  1.73,  0.12,  1.73, -0.23,  0.35,
        1.73, -1.05,  1.33, -1.09,  0.28,  0.32, -1.14, -1.79,  0.97,
        1.55, -0.13,  1.91,  0.69, -0.28, -0.18, -0.75, -0.9 ,  0.63,
        1.57,  0.17,  1.02, -1.58, -1.32,  1.98, -0.26, -1.64, -0.84,
       -0.56, -1.93,  0.6 , -0.89, -1.06,  0.04,  1.41, -1.75, -0.75,
       -0.47, -0.83,  1.22,  0.21,  0.24, -0.95, -0.07,  0.95,  1.3 ,
       -1.9 ,  1.22,  1.09, -0.85,  1.05,  1.44,  0.28, -0.12, -1.65,
        0.92,  0.29,  0.4 , -0.51,  0.04,  0.15, -2.21, -1.37,  1.48,
        0.76, -0.38, -0.09, -0.71,  1.57,  0.92, -0.1 ,  0.13, -1.03,
        0.46], dtype=float32)

In [130]:
compressed_pickle("word2vec_bz2file_decimal", model2)

In [134]:
def avgword2vec1(doc):
    return np.mean([model2[word] for word in doc if word in model2.index_to_key],axis=0)

In [135]:
X1=[]
for i in tqdm(range(len(words))):
    X1.append(avgword2vec1(words[i]))

100%|████████████████████████████████████████████████████████████████████████████| 50000/50000 [31:30<00:00, 26.44it/s]


In [136]:
model2.index_to_key

['br',
 'movie',
 'film',
 'one',
 'like',
 'time',
 'good',
 'character',
 'story',
 'even',
 'get',
 'would',
 'make',
 'see',
 'really',
 'scene',
 'well',
 'much',
 'bad',
 'people',
 'great',
 'also',
 'first',
 'show',
 'way',
 'thing',
 'made',
 'life',
 'could',
 'think',
 'go',
 'know',
 'watch',
 'love',
 'plot',
 'actor',
 'two',
 'many',
 'seen',
 'year',
 'say',
 'end',
 'never',
 'acting',
 'look',
 'best',
 'little',
 'ever',
 'man',
 'better',
 'take',
 'come',
 'work',
 'still',
 'part',
 'something',
 'director',
 'find',
 'want',
 'back',
 'give',
 'lot',
 'real',
 'guy',
 'watching',
 'performance',
 'woman',
 'play',
 'old',
 'funny',
 'though',
 'another',
 'actually',
 'role',
 'nothing',
 'going',
 'new',
 'every',
 'girl',
 'day',
 'world',
 'point',
 'cast',
 'horror',
 'minute',
 'comedy',
 'thought',
 'fact',
 'feel',
 'quite',
 'pretty',
 'star',
 'action',
 'around',
 'seems',
 'young',
 'big',
 'however',
 'got',
 'enough',
 'right',
 'long',
 'line',
 'f

In [137]:
X1_new = np.array(X1)
X1_new.shape

(50000, 100)

In [138]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1_new, y, test_size = 0.20, random_state = 0)

In [139]:
rfc = RandomForestClassifier(criterion='entropy', n_estimators=300)

In [140]:
rfc.fit(X1_train, y1_train)

RandomForestClassifier(criterion='entropy', n_estimators=300)

In [141]:
y_pred2 = rfc.predict(X1_test)

In [142]:
score=accuracy_score(y1_test,y_pred2)
print(score)

0.833


In [144]:
compressed_pickle("review_classifier_model", rfc)

In [102]:
model1.wv==x

True

In [100]:
x['king']

array([-1.7916073 ,  0.39673504, -0.7527301 , -0.88069326,  0.23557387,
       -1.3942405 ,  0.3816136 ,  0.18450025, -0.8303827 ,  0.82364345,
       -1.1227267 , -0.85762465,  0.29456764,  0.581786  ,  0.3304755 ,
        0.3067833 , -1.3680676 , -1.760744  , -1.4201983 , -0.683725  ,
       -2.2025824 , -1.3758914 ,  1.6227067 , -0.6203595 ,  0.14728004,
       -0.8543858 , -1.9281954 , -0.9384264 , -0.23511815,  0.25570595,
        2.3697062 , -1.1228553 ,  0.6284109 , -0.65249354,  1.971913  ,
       -1.314398  ,  0.17824186, -0.66040516,  0.07912144, -1.1437658 ,
        1.1693095 , -0.33764693,  0.27976593, -0.7348727 ,  0.3053981 ,
       -0.70772696,  0.69819546, -1.228625  , -1.5835164 , -0.81319404,
        0.57749426,  1.6408365 , -0.0219146 ,  1.3130064 , -1.0657222 ,
        1.6303095 ,  0.00499786,  0.53303236, -3.3025374 , -1.0137596 ,
       -0.53677446, -0.9982146 , -1.0254186 ,  1.1907377 , -0.26748604,
       -0.6581822 ,  1.2045606 ,  0.05325426,  1.4532279 , -0.22

In [26]:
X_new = np.array(X)
X_new.shape

(50000, 100)

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn import naive_bayes
from sklearn.metrics import roc_auc_score,accuracy_score

In [29]:
data['sentiment'] = pd.get_dummies(data['sentiment'],drop_first=True)
data['sentiment']

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 50000, dtype: uint8

In [30]:
y=data['sentiment']

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X_new, y, test_size = 0.20, random_state = 0)

In [32]:
from sklearn.ensemble import RandomForestClassifier
review_imdb_detect_model = RandomForestClassifier()
review_imdb_detect_model.fit(X_train, y_train)

RandomForestClassifier()

In [33]:
y_pred=review_imdb_detect_model.predict(X_test)

In [37]:
X_test.shape

(10000, 100)

In [35]:
score=accuracy_score(y_test,y_pred)
print(score)

0.8404


In [43]:
params = {'n_estimators':[100,200,300],
                     'criterion':['gini','entropy']}


In [44]:
from sklearn.model_selection import GridSearchCV

In [45]:
grid = GridSearchCV(RandomForestClassifier(),params,cv=5,verbose=2)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV] criterion=gini, n_estimators=100 ................................


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


[CV] ................. criterion=gini, n_estimators=100, total=  48.8s
[CV] criterion=gini, n_estimators=100 ................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   48.8s remaining:    0.0s


[CV] ................. criterion=gini, n_estimators=100, total=  46.1s
[CV] criterion=gini, n_estimators=100 ................................
[CV] ................. criterion=gini, n_estimators=100, total=  46.2s
[CV] criterion=gini, n_estimators=100 ................................
[CV] ................. criterion=gini, n_estimators=100, total=  44.7s
[CV] criterion=gini, n_estimators=100 ................................
[CV] ................. criterion=gini, n_estimators=100, total=  44.9s
[CV] criterion=gini, n_estimators=200 ................................
[CV] ................. criterion=gini, n_estimators=200, total= 1.5min
[CV] criterion=gini, n_estimators=200 ................................
[CV] ................. criterion=gini, n_estimators=200, total= 1.5min
[CV] criterion=gini, n_estimators=200 ................................
[CV] ................. criterion=gini, n_estimators=200, total= 1.6min
[CV] criterion=gini, n_estimators=200 ................................
[CV] .

[Parallel(n_jobs=1)]: Done  30 out of  30 | elapsed: 70.6min finished


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [46]:
grid.best_estimator_

RandomForestClassifier(criterion='entropy', n_estimators=300)

In [47]:
grid.best_score_

0.8471

In [49]:
import pickle

In [108]:
model = RandomForestClassifier(criterion='entropy', n_estimators=300)

In [109]:
model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=300)

In [110]:
y_pred1 = model.predict(X_test)

In [111]:
score=accuracy_score(y_test,y_pred1)
print(score)

0.842


In [55]:
pickle.dump(model,open('RFC_NPL.pkl','wb'))

In [56]:
input_dim = 100

In [145]:
y1_train = np.array(y1_train)

In [57]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

In [146]:
ann = Sequential()
ann.add(Dense(8, input_dim = input_dim, kernel_initializer='normal', activation='relu'))
ann.add(Dense(5, activation = "relu", kernel_initializer='normal'))
ann.add(Dense(1, activation = 'sigmoid'))

In [147]:
ann.compile(optimizer = Adam(learning_rate = 0.001),
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])

In [148]:
result = ann.fit(X1_train, y1_train,validation_split=0.33, epochs = 20, batch_size = 10)

Epoch 1/20
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
2670/2680 [============================>.] - ETA: 0s - loss: 0.3775 - accuracy: 0.8377WARNING:tensorflow:AutoGraph could not transform <function Model.make_test_function.<locals>.test_function at 0x0000029BCF0CB4C8> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=1

In [149]:
ypred3 = ann.predict(X1_test)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
313/313 [==============================] - 1s 3ms/step


In [154]:
ypred3 = (ypred3 > 0.5)

In [155]:
score=accuracy_score(np.array(y_test),ypred3)
print(score)

0.8596


In [156]:
compressed_pickle("review_classifier_ann", ann)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 'arguments' object has no attribute 'posonlyargs'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity t

In [161]:
ann.save('ann.h5')

In [36]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84      4897
           1       0.85      0.83      0.84      5103

    accuracy                           0.84     10000
   macro avg       0.84      0.84      0.84     10000
weighted avg       0.84      0.84      0.84     10000



In [23]:
z = 'Jesus Christ! Not only does this film reach our expectations as a film, it surpasses them. There are quite a few things I like about this film so this review may take a while to read.Firstly, the Russo brothers obviously show deep appreciation for the MCU and the effort they put in for this film is clearly visible with so many awesomely-handled pivotal moments in the films plot. It seems that many of the MCUs best films are directed by Anthony and Joe Russo and that doesnt surprise me one bit.'

In [171]:
def sentiment_analysis(z):    
    corpus1=[]
    for i in range(0,1):
        review = re.sub('[^a-zA-Z]', ' ', z)
        review = review.lower()
        review = review.split()
        review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')]
        review = ' '.join(review)
        corpus1.append(review)
    words2 = []
    for i in corpus1:
        sent_token = sent_tokenize(i)
        for j in sent_token:
            words2.append(simple_preprocess(j))
    x = np.array( np.mean([model1.wv[word] for word in words2[0] if word in model1.wv.index_to_key],axis=0))
    ans = ann.predict(x.reshape(1,100))
    ans = (ans > 0.5)
    return ans[0][0]

In [172]:
sentiment_analysis(z)

1/1 [==============================] - 2s 2s/step


False

In [162]:
z="Im not sure what accomplished director/producer/cinematographer Joshua Caldwell was thinking taking on this project.This film has got to be the epitome of terrible writing and should be a classroom example of 'what not to do' when writing a screenplay. Why would Joshua take on (clearly) amateur writer Adam Gaines script is beyond me. Even his good directing and excellent cinematography could not save this disaster."

In [117]:
v="This film is an emotional rollercoaster with some of the coolest superhero plot lines ever drawn up. It's straight up the most epic Marvel film that will probably ever be created. I don't see how Marvel could ever top this, but getting to see these characters all together at least one last time was a reward all on its own."

In [48]:
import pickle

In [125]:
!pip install dill

In [49]:
pickle.dump(review_imdb_detect_model,open('npl_model.pkl','wb'))

In [167]:
model1.wv['movie']

array([ 0.2 , -0.25, -1.35, -0.23,  0.92,  0.79,  1.46,  0.33, -0.06,
        0.2 ,  0.68,  1.75, -1.39,  1.92,  0.07, -0.35,  1.22,  1.06,
       -3.66,  0.18, -0.08,  0.24,  2.13, -0.57,  1.12, -0.23, -0.79,
        1.61, -0.25,  1.5 , -0.57, -1.85,  0.91, -1.21, -1.37,  0.63,
        1.79,  0.36,  2.45,  1.81,  0.39, -0.47,  0.07, -0.57,  0.36,
        0.63,  0.14,  0.97, -1.17, -0.65,  1.19, -0.44, -0.51, -0.92,
       -0.4 , -1.63,  0.65, -1.18, -0.52,  0.69,  0.52, -0.68, -1.1 ,
       -0.72, -0.21,  1.4 ,  0.28, -0.07, -0.52,  0.83,  0.93,  1.6 ,
       -2.6 ,  1.24,  2.18, -1.61, -0.11,  1.76,  0.83, -0.56, -1.74,
        1.08,  0.24,  0.98, -0.64,  0.21,  1.45, -2.26, -2.14,  0.36,
        1.07, -1.4 ,  0.7 , -0.33,  1.62,  0.2 ,  0.44, -0.31, -0.97,
        0.6 ], dtype=float32)